laws:
  - 해양경찰법
  - 해양경비법
  - 수상에서의 수색ㆍ구조 등에 관한 법률
  - 수상레저안전법
  - 선박안전법
  - 선박법
  - 선박직원법
  - 선원법
  - 해양환경관리법
  - 해양폐기물 및 해양오염퇴적물 관리법
  - 해양공간계획 및 관리에 관한 법률
  - 공유수면 관리 및 매립에 관한 법률
  - 수산업법
  - 수산자원관리법
  - 원양산업발전법
  - 양식산업발전법
  - 어선법
  - 어선원 및 어선 재해보상보험법
  - 낚시 관리 및 육성법
  - 해양사고의 조사 및 심판에 관한 법률
  - 항만법
  - 항만운송사업법
  - 마리나항만의 조성 및 관리 등에 관한 법률
  - 항로표지법
  - 해사안전기본법
  - 해상교통안전법
  - 해양수산발전 기본법
  - 해양과학조사법
  - 도선법
  - 해운법
  - 유선 및 도선 사업법
  - 항만지역등 대기질 개선에 관한 특별법
  - 국제항해선박 및 항만시설의 보안에 관한 법률
  - 선박의 입항 및 출항 등에 관한 법률
  - 선박평형수(船舶平衡水) 관리법
  - 해양심층수의 개발 및 관리에 관한 법률
